name: Trigger auto deployment for quant-api

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/quant-api-AutoDeployTrigger-5eeb3c97-b000-448f-8dd8-bdae97cdf585.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.QUANTAPI_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.QUANTAPI_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.QUANTAPI_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          # 1. 指向原始碼所在的 src 資料夾
          appSourcePath: ${{ github.workspace }}/src
          
          # 2. 指定 Dockerfile 的相對路徑 (相對於上面的 src)
          dockerfilePath: QuantTrading.Api/Dockerfile
          
          # 3. 登錄設定
          registryUrl: registryquant2026.azurecr.io
          registryUsername: ${{ secrets.QUANTAPI_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.QUANTAPI_REGISTRY_PASSWORD }}
          
          # 4. 目標設定
          containerAppName: quant-api
          resourceGroup: rg-quant-trading
          imageToBuild: registryquant2026.azurecr.io/quant-api:${{ github.sha }}

